# This is a basic workflow to help you get started with Actions

name: collect comments

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  collect-comments:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug
        run: cat $GITHUB_EVENT_PATH

      - name: Collect PR comments
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          COMMENTS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                       "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments")
          echo "Comments from PR #$PR_NUMBER:"
          echo "$COMMENTS" | jq -r -c '.[] | "User: \(.user.login), Comment: \(.body)"'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
