name: Your Workflow

on:
  pull_request:
    types:
      - opened
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  your-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get PR number
      id: pr_number
      run: echo "PR_NUMBER=${{ github.event.number }}" >> $GITHUB_ENV

    - name: Use PR number
      run: echo "The pull request number is $PR_NUMBER"
