name: Your Workflow

on:
  pull_request_target:
    types:
      - opened
      - synchronize  # This type is triggered when a new commit is pushed to the branch of the pull request
  workflow_dispatch:

jobs:
  your-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Debug GitHub context
      run: echo "${{ toJson(github) }}"

    - name: Get PR number
      id: pr_number
      run: |
        PR_NUMBER=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }}" \
          | jq -r .number)
        echo "PR_NUMBER=${PR_NUMBER}" >> $GITHUB_ENV

    - name: Use PR number
      run: echo "The pull request number is $PR_NUMBER"
