name: Collect comments in pull requests from peer review

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  collect-comments:
    # runs-on: [ self-hosted, autoscaling-runner ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Collect PR comments
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "Comments from PR #$PR_NUMBER:"
          
          COMMENTS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                       "${GITHUB_API_URL}/repos/${{ github.repository }}/pulls/$PR_NUMBER/comments")
         
          echo "GitHub API Response:"
          echo "$COMMENTS"
          
          # Debug: Print the length of COMMENTS
          echo "Length of COMMENTS: ${#COMMENTS}"
          # Check if there are no comments
          if [ -z "$COMMENTS" ]; then
            echo "There are no comments" >> comments.csv
          else
            # Initialize variables to track the current file
            CURRENT_FILE=""
            FIRST=true
      
            # Use jq to process each COMMENT
            echo "$COMMENTS" | jq -r -c '.[] | "(\(.path), line \(.position), 0) #todo \(.body)"' | while IFS= read -r COMMENT; do
              FILE=$(echo "$COMMENT" | cut -d',' -f1)
        
              # Check if the file has changed
              if [ "$FILE" != "$CURRENT_FILE" ]; then
                # Print the filename only if it's not the first file
                if [ "$FIRST" = false ]; then
                  echo
                else
                  FIRST=false
                fi
                CURRENT_FILE="$FILE"
                echo "$CURRENT_FILE" >> comments.csv
              fi
              
              # Print the comment
              echo "$COMMENT" | cut -d',' -f2- >> comments.csv
            done
          fi
            
            # for COMMENT in $(echo "$COMMENTS" | jq -c '.[]'); do
            #   # Debug: Print each COMMENT
            #   echo "Current COMMENT: $COMMENT"
            
            #   # Extract data from the comment using jq
            #   POSITION=$(echo "$COMMENT" | jq -r '.position')
            #   BODY=$(echo "$COMMENT" | jq -r '.body')
            #   FILE=$(echo "$COMMENT" | jq -r '.path')
              
            #   # Check if the file has changed
            #   if [ "$FILE" != "$CURRENT_FILE" ]; then
            #     echo "$FILE" >> comments.csv
            #     CURRENT_FILE="$FILE"
            #   fi
              
            #   # Append the comment to the CSV file
            #   echo "(line $POSITION, 0) #todo $BODY" >> comments.csv
          # fi
      # TODO: Upload CSV should be run in a seperated job
      - name: Upload CSV to workspace
        uses: actions/upload-artifact@v2
        with:
          name: comments
          path: comments.csv
      
  # upload-csv:
  #   needs: collect-comments
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Display current working directory
  #       run: pwd

  #     - name: List files
  #       run: ls -R
        
  #     - name: Upload CSV
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: comments
  #         path: comments.csv

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
